---
variables:
  files: src/bluecat_bam tests samples/*.py *.py

stages:
  - code-quality
  - test

black:
  image: python:3.7-stretch
  stage: code-quality
  before_script:
    - pip install black
  script:
    - black --check --diff $files

flake8-py37:
  image: python:3.7-stretch
  stage: code-quality
  before_script:
    - pip install flake8
  script:
    - flake8 $files

pylint-py37:
  image: python:3.7-stretch
  stage: code-quality
  before_script:
    - pip install pylint==2.14.1 pytest requests xmltodict
    - pip install .
  script:
    - pylint $files

bandit:
  stage: code-quality
  image: python:latest
  script:
  - pip install bandit
  - bandit -s B101 -r $files

test-py35:
  image: python:3.5-stretch
  stage: test
  before_script:
    - pip install pytest-cov pytest-mock
    - pip install -e .
  script:
    - pytest --cov=src

test-py36:
  image: python:3.6-stretch
  stage: test
  before_script:
    - pip install pytest-cov pytest-mock
    - pip install -e .
  script:
    - pytest --cov=src

test-py37:
  image: python:3.7-stretch
  stage: test
  before_script:
    - pip install pytest-cov pytest-mock
    - pip install -e .
  script:
    - pytest --cov=src
